### ISSUE TITLE
IPv6 Homestead fails to connect to Cassandra.

### ISSUE THREAD

**Issue by ghost** [Metaswitch/homestead#13]
Homestead connects to "localhost" to connect to cassandra.  On a pure IPv6 system this fails.  Fixed up by adding a command line option tell homestead cassandra's IP address and specifying the external IPv6 address fixes the connection.  Not seen on a system which has IPv4 and IPv6.

We need to understand why "localhost" does not work.

**Comment by sathiyan-sivathas** [comment]
Fixed by Metaswitch/clearwater-infrastructure#369
