### ISSUE TITLE
Homestead restart when shutdown is slow causes subsequent Monit failures

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/homestead#149]
I saw an instance where SAS was misconfigured, so we hit https://github.com/Metaswitch/sas-client/issues/37. Running "sudo monit restart homestead" then put Homestead into a state where all ports were shut down but the main process was still running. This caused the poll_homestead Monit process to treat this as a failure and run "/etc/init.d/homestead abort", which happened after the "start" part of "monit restart homestead".

If this had been done with "sudo service homestead stop" (the recommended method), this would probably have been fine, as the "/etc/init.d/homestead start" would run after the "/etc/init.d/homestead abort" - so this is low priority.

Still, it might be nice to have this work more nicely - maybe by having monit's "stop homestead" instruction also cover stopping poll_homestead, or maybe by fixing monit to support IPv6 and doing away with the separate poll_* scripts (although this would reduce our flexibility to do things like treat 503 responses from Sprout as successes without separate Monit work).

Homestead logs:

```
26-08-2014 16:08:55.694 Status httpstack.cpp:211: Stopping HTTP stack
26-08-2014 16:08:55.694 Status httpstack.cpp:218: Waiting for HTTP stack to stop
[snip]
26-08-2014 16:08:56.159 Debug zmq_lvc.cpp:107: Unbinding and closing statistics socket inproc://H_rejected_overload
26-08-2014 16:09:21.629 Debug sas.cpp:390: Failed to connect to address: 
26-08-2014 16:09:21.629 Error sas.cpp:402: Failed to connect to SAS 10.139.10.248:6761 : 115 Operation now in progress
26-08-2014 16:09:21.629 Debug sas.cpp:323: Waiting to reconnect to SAS - timeout = 10000
26-08-2014 16:09:21.630 Status cache.cpp:160: Stopping cache
26-08-2014 16:09:21.633 Status cache.cpp:170: Waiting for cache to stop
26-08-2014 16:09:26.359 Status main.cpp:374: Access logging enabled to /var/log/homestead
26-08-2014 16:09:26.360 Status main.cpp:378: Log level set to 5
26-08-2014 16:09:26.360 Debug zmq_lvc.cpp:65: Initializing statistics aggregator
```

Monit logs:

```
[UTC Aug 26 16:08:55] info     : 'homestead' restart on user request
[UTC Aug 26 16:08:55] info     : monit daemon with PID 1514 awakened
[UTC Aug 26 16:08:55] info     : Awakened by User defined signal 1
[UTC Aug 26 16:08:55] info     : 'homestead' trying to restart
[UTC Aug 26 16:08:55] info     : 'homestead' stop: /etc/init.d/homestead
[UTC Aug 26 16:09:22] info     : 'homestead' start: /etc/init.d/homestead
[UTC Aug 26 16:09:22] info     : 'homestead' restart action done
[UTC Aug 26 16:09:22] error    : 'poll_homestead' HTTP failed to http://172.30.0.74:8888/ping

[UTC Aug 26 16:09:32] error    : 'poll_homestead' HTTP failed to http://172.30.0.74:8888/ping

[UTC Aug 26 16:09:32] info     : 'poll_homestead' exec: /etc/init.d/homestead
```
```

**Comment by rkd-msw** [comment]
I've raised https://github.com/Metaswitch/sas-client/pull/50, which should stop Homestead (or other node types) from shutting down slowly if SAS is misconfigured. That was the only cause of a slow shutdown that I know of.

**Comment by eleanor-merry** [comment]
Doc updates covered by https://github.com/Metaswitch/clearwater-readthedocs/pull/16
