### ISSUE TITLE
Got 404 error when creating subscriptions using the REST API

### ISSUE THREAD

**Issue by seanguo** [Metaswitch/homestead#156]
We switched to the new AMI for the all-in-one Ec2 installation since the old AMI is not available. But currently we got 404 HTTP response when creating the subscriptions using the REST API. So have you changed something? Where can I find the documentation?
FYI, I'm using the following HTTP request to do that:
        digest = Digest::MD5.hexdigest("#{private_id}:#{@realm}:#{password}")
        @client.put("http://localhost:8888/private/#{private_id}", { :digest_ha1 => digest })
Thanks.

**Comment by eleanor-merry** [comment]
Closing as can't be reproduced
