### ISSUE TITLE
Unexpected call failures during Homestead recovery

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/homestead#177]
While running 2 CPS traffic on a duplex Clearwater configuration, Homestead-2 was powered off then back on. The system was not impacted by the power off, but a few call failures occurred when Homestead-2 was powered back on. One 404 Not Found, with SAS indicating "Error sending to 192.168.140.197:8888 Couldn't connect to server (7)". Two 480 Temporarily Unavailable, with SAS indicating: "Failed to retrieve location information for subscriber from the HSS". The number of errors varies from test to test, but is always just a couple.

Note that no errors occur when a Homestead node is isolated from the network then reconnected to the network. This may indicated that HTTP REST requests are accepted before the service is completely restored?

**Comment by mirw** [comment]
I suspect that the HSS connection hasn't yet been established.  It looks as though we return a 404 in this scenario (meaning sprout won't retry).  Instead, we should probably return a 503 indicating that we weren't connected to the HSS, but someone else might be.

**Comment by rkd-msw** [comment]
Is there not still some code that always interprets a 503 error as "upstream overloaded"?

**Comment by mirw** [comment]
Possibly.  Maybe we need another return code.  My point is that one Homestead node's local failure of an HSS connection should not be considered a fatal error by Sprout.

**Comment by rkd-msw** [comment]
Yes, agreed - just wanted to point out that there might be unexpected consequences to returning 503.

**Comment by mirw** [comment]
I've just read the code, and actually there doesn't seem to be such behavior.

*   If *both* requests fail with 503, we increment penalties.  *Both* requests shouldn't fail in this way - if they do, chances are that something is wrong.
*   If any request fails with 504 (as it would have done prior to my proposed fix), we increment penalties.  This was wrong behavior, but changing the return code will fix it.

So I think this will actually just fix the problem.

As with any code change, though, whoever fixes this should test it.

**Comment by graemerobertson** [comment]
I think this was essentially the same as https://github.com/Metaswitch/homestead/issues/273, which has been fixed by https://github.com/Metaswitch/homestead/pull/303, so I'm going to close this issue.
