### ISSUE TITLE
Impu location lookup request always returns contents of scscf_uri when no HSS is provisioning even when the protocol is not SIP

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/homestead#183]
I have a system using homestead-prov as the subscriber store. When sprout receives an INVITE to a tel uri, it asks homestead for the location of the tel uri  and homestead always responds with the /etc/clearwater/config setting for the scscf_uri variable. This seems to be wrong in the case of a tel uri since it prevents sprout from doing an ENUM dip to translate the tel uri to a sip uri, so the call fails.

In my build I've changed homestead/src/handlers.cpp (method ImpuLocationInfoTask::run) to respond with a 404 if there's no HSS and the protocol is not sip. This fixes my immediate problem, but I defer to PC for a "real" fix.

**Comment by mirw** [comment]
Is this a duplicate of #178 (fixed last week)?

**Comment by dtheobald** [comment]
Yes, as far as I can tell by eyeballing the fix for #178, this issue is a duplicate.
