### ISSUE TITLE
Error log when upgrading homestead (Connection error: Could not connect to localhost:9160)

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/homestead#209]
I upgraded a homestead node using knife (by running `chef-client` followed by `clearwater-upgrade`). I got a log about being unable to contact Cassandra. The upgrade seemed to proceed OK, but we shouldn't have errors in our upgrade logs. 

Output from knife can be found here: https://gist.github.com/AlexHockey/784e17232979c8bd2789

**Comment by eleanor-merry** [comment]
Superseded by https://github.com/Metaswitch/homestead/issues/333
