### ISSUE TITLE
Creating keyspaces doesn't wait for Cassandra to start

### ISSUE THREAD

**Issue by bossmc** [Metaswitch/homestead#22]
The current installation instructions advise installing Homer/Homestead at the same time as installing Cassandra, this can lead to the keyspaces being configured before Cassandra is listening on port 9160.

When this happens, `dpkg`/`apt-get` bails out of the install and doesn't start the homestead service.

A workaround is to run `sudo apt-get install -f` which will complete the homestead install, creating the keyspaces and starting the homestead service.

This issue also applies to Homer and the Homestead Provisioning component and should be fixed there at the same time as fixing it for Homestead.

**Comment by rkd-msw** [comment]
Think this is fixed by https://github.com/Metaswitch/crest/pull/178 (and similar changes elsewhere). @bossmc , do you agree?

**Comment by bossmc** [comment]
Agreed.
