### ISSUE TITLE
Homestead's connection to SAS drops

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/homestead#224]
I set up a homestead to log to SAS. When the node started netstat showed homestead was connected to SAS. 

```
[homestead-1]ubuntu@ec2-54-221-130-180:~$ sudo netstat -plan | grep 6761
tcp        0      0 10.151.32.44:44636      10.234.16.34:6761       ESTABLISHED 12068/homestead
```

After a few minutes the connection drops and is not re-established. 

```
[homestead-1]ubuntu@ec2-54-221-130-180:~$ sudo netstat -plan | grep 6761
tcp        1      0 10.151.32.44:44636      10.234.16.34:6761       CLOSE_WAIT  12068/homestead
```

Wire trace shows that SAS sends a FIN to homestead (presumably because homestead is not sending heartbeat messages to SAS as the sas-client does not support that). However homestead never re-establishes the connection even when you make a call. 

This feels like it will end up being an issue with the SAS client library, but I'm raising here as I've only ever seen the problem on a homestead node.

**Comment by rkd-msw** [comment]
I suspect the reason we only see it on Homestead is that Sprout and Bono will log the Monit options poll to SAS every ten seconds (https://github.com/Metaswitch/sprout/issues/677).

**Comment by AlexHockey** [comment]
Possibly, though I've never seen the problem with Ralf either.

**Comment by graemerobertson** [comment]
@AlexHockey are you ok to close this given https://github.com/Metaswitch/sas-client/pull/53? I've also just run `sudo netstat -plan | grep 6761` on the staging Homestead node and it is connected to SAS.

**Comment by AlexHockey** [comment]
Given the test you just mentioned, yes I am happy to close.
