### ISSUE TITLE
eval on start-stop-daemon in homestead's init.d script exceeds line limit?

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/homestead#263]
Using eval in homestead's init.d script causes as error that appears to be some kind of line length limit. For example, running the following causes an error in the script:
```
eval start-stop-daemon --start --quiet --background --make-pidfile --pidfile /var/run/homestead.pid --exec /usr/share/clearwater/bin/homestead --chuid homestead --chdir /etc/clearwater -- --localhost=192.168.159.169 --home-domain=os3.richlab.datcon.co.uk --diameter-conf=/var/lib/homestead/homestead.conf --dns-server=192.168.159.161 --http=192.168.159.169 --http-threads=100 --dest-realm=os3.richlab.datcon.co.uk --dest-host=0.0.0.0 --hss-peer= --max-peers=2 '--server-name=sip:sprout.os3.richlab.datcon.co.uk;transport=TCP' --impu-cache-ttl=0 --hss-reregistration-time=1800 --sprout-http-name=sprout.os3.richlab.datcon.co.uk:9888 --scheme-unknown=unknown --alarms-enabled --access-log=/var/log/homestead --log-file=/var/log/homestead --log-level=5 --sas=sas.os3.richlab.datcon.co.uk,homestead@homestead-1.os3.richlab.datcon.co.uk
bash: --impu-cache-ttl=0: command not found
```
While running it without using eval works fine.

I've removed the eval in my local version since I don't think it's needed anyway.

**Comment by rkd-msw** [comment]
The `eval` is needed to allow some of the command-line parameters to contain spaces - see https://github.com/Metaswitch/homestead/pull/260#issue-109495907 for more context.

I noticed that the parameter right before the one in the 'command not found' error is `'--server-name=sip:sprout.os3.richlab.datcon.co.uk;transport=TCP'  --impu-cache-ttl=0`. Do you know why that particular option (and only that one) is in single quotes?

(I'm also wondering if the semicolon is causing issues - I'll look into that).

**Comment by dtheobald** [comment]
I believe that bash is doing that since the string contains a semi-colon.

The variable assignment in share_config looks like this:
```
scscf_uri="sip:sprout.${home_domain};transport=TCP"
```

**Comment by dtheobald** [comment]
You are correct about it being the semi-colon cause the problem. I just tried a simple eval with a semi-colon (in single quotes) and it didn't work as i'd have expected.

**Comment by dtheobald** [comment]
I did some research and found that using arrays (instead of eval) was the way to overcome issue #260. I made the following changes to homestead.init.d and some testing with scheme_args and all looked well to me:
```
--- a/debian/homestead.init.d
+++ b/debian/homestead.init.d
@@ -161,8 +161,8 @@ get_daemon_args()
         fi
 
         [ "$hss_mar_lowercase_unknown" != "Y" ] || scheme_args="--scheme-unknown=unknown"
-        [ "$hss_mar_force_digest" != "Y" ] || scheme_args="--scheme-unknown=\"SIP Digest\" --scheme-aka=\"SIP Digest\""
-        [ "$hss_mar_force_aka" != "Y" ] || scheme_args="--scheme-unknown=Digest-AKAv1-MD5 --scheme-digest=Digest-AKAv1-MD5"
+        [ "$hss_mar_force_digest" != "Y" ] || scheme_args=(--scheme-unknown="SIP Digest" --scheme-aka="SIP Digest")
+        [ "$hss_mar_force_aka" != "Y" ] || scheme_args=(--scheme-unknown=Digest-AKAv1-MD5 --scheme-digest=Digest-AKAv1-MD5)
 
         [ -z "$diameter_timeout_ms" ] || diameter_timeout_ms_arg="--diameter-timeout-ms=$diameter_timeout_ms"
         [ -z "$signaling_namespace" ] || namespace_prefix="ip netns exec $signaling_namespace"
@@ -180,7 +180,7 @@ get_daemon_args()
 
         [ "$sas_compression_enabled" != "Y" ] || sas_compression_enabled_arg="--sas-compression-enabled"
 
-        DAEMON_ARGS="--localhost=$local_ip
+        DAEMON_ARGS=(--localhost=$local_ip
                      --home-domain=$home_domain
                      --diameter-conf=/var/lib/homestead/homestead.conf
                      --dns-server=$signaling_dns_server
@@ -194,7 +194,7 @@ get_daemon_args()
                      --impu-cache-ttl=$impu_cache_ttl
                      --hss-reregistration-time=$hss_reregistration_time
                      --sprout-http-name=$sprout_http_name
-                     $scheme_args
+                     "${scheme_args[@]}"
                      $diameter_timeout_ms_arg
                      $alarms_enabled_arg
                      $target_latency_us_arg
@@ -206,11 +206,11 @@ get_daemon_args()
                      --log-file=$log_directory
                      --log-level=$log_level
                      --sas=$sas_server,$NAME@$public_hostname
-                     $sas_compression_enabled_arg"
+                     $sas_compression_enabled_arg)
 
 
-        [ "$http_blacklist_duration" = "" ]     || DAEMON_ARGS="$DAEMON_ARGS --http-blacklist-duration=$http_blacklist_duration"
-        [ "$diameter_blacklist_duration" = "" ] || DAEMON_ARGS="$DAEMON_ARGS --diameter-blacklist-duration=$diameter_blacklist_duration"
+        [ "$http_blacklist_duration" = "" ]     || DAEMON_ARGS=("${DAEMON_ARGS[@]}" --http-blacklist-duration=$http_blacklist_duration)
+        [ "$diameter_blacklist_duration" = "" ] || DAEMON_ARGS=("${DAEMON_ARGS[@]}" --diameter-blacklist-duration=$diameter_blacklist_duration)
 }
 
 #
@@ -228,7 +228,7 @@ do_start()
         # daemon is not running, so attempt to start it.
         setup_environment
         get_daemon_args
-        $namespace_prefix start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON --chuid $NAME --chdir $HOME -- $DAEMON_ARGS \
+        $namespace_prefix start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON --chuid $NAME --chdir $HOME -- "${DAEMON_ARGS[@]}" \
                 || return 2
         # Add code here, if necessary, that waits for the process to be ready
         # to handle requests from services started subsequently which depend
@@ -268,7 +268,7 @@ do_run()
 {
         setup_environment
         get_daemon_args
-        $namespace_prefix start-stop-daemon --start --quiet --exec $DAEMON --chuid $NAME --chdir $HOME -- $DAEMON_ARGS \
+        $namespace_prefix start-stop-daemon --start --quiet --exec $DAEMON --chuid $NAME --chdir $HOME -- "${DAEMON_ARGS[@]}" \
                 || return 2
 }
```

**Comment by dtheobald** [comment]
The diff is missing that I changed it from executing as /bin/sh to /bin/bash

**Comment by rkd-msw** [comment]
Thanks! I've investigated separately, and found that using quotes in the init.d script resolves the issue. Can you confirm that https://github.com/Metaswitch/homestead/pull/264 fixes the issue you were seeing? If so, I'll raise a separate issue to use `eval` and quotes in all our init.d scripts, for consistency.

**Comment by dtheobald** [comment]
Yeah, I tried that too (and it works), but since using ```eval``` is generally frowned upon, I went looking for something else that would work without it.

**Comment by rkd-msw** [comment]
I'm a bit cautious that Bash arrays are going to be unfamiliar to most people - less familiar than quoting variables, at least - and so using them will make the code harder to maintain.

I'm not sure what the disadvantages of `eval` are in this situation - in particular, I don't think the most common concern (about allowing code injection) applies, as local_config and shared_config are Bash scripts, and so if a malicious user was in a position to add `local_ip="1.2.3.4;rm -rf /"`, they could just add `rm -rf /` to the file and have it executed. Did you have any specific issues that you've seen as a result of Homestead using `eval` here?

**Comment by dtheobald** [comment]
I'm just not a fan of escaping and someone needing to be aware of it for some args and not others. If all the args were arrays and DAEMON_ARGS was an array there'd be no need for escaping and adding new args would just work as long as it followed the array pattern. So for me it's more of a maintenance thing.

**Comment by rkd-msw** [comment]
Yep, agreed that it's going to be painful if users have to know/remember which arguments are quoted (and therefore allow semicolons). I've raised https://github.com/Metaswitch/homestead/issues/266 to track that we should quote all our arguments, to allow consistent treatment and ease maintenance.
