### ISSUE TITLE
SRV priority interactions in Diameter don't work for A records

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/homestead#274]
I learnt a Diameter peer by IP address, not by SRV lookup. Routing to it failed. This was because the priority value of the AddrInfo was uninitialized, so my peer score of 98 fell to around -32000, and peers scoring below 0 are ignored by freeDiameter.

This suggests a follow-on problem - if a SRV record has a high priority (e.g. 5000), it'll be ignored (wrongly).

**Comment by graemerobertson** [comment]
So this is now fixed, right?

**Comment by rkd-msw** [comment]
Yep.
