### ISSUE TITLE
No cached av found in Database impi 

### ISSUE THREAD

**Issue by lewang0418** [Metaswitch/homestead#298]
Hi,

I am having issues with manual Clearwater installation. 

The log on Homestead node shows that 

> 28-01-2016 14:00:05.612 UTC Warning (Net-SNMP): Warning: Failed to connect to the agentx master agent ([NIL]): 
28-01-2016 14:00:12.138 UTC Verbose httpstack.cpp:286: Process request for URL /impi/6505550009%40example.com/av, args impu=sip%3A6505550009%40example.com
28-01-2016 14:00:12.138 UTC Debug handlers.cpp:148: Parsed HTTP request: private ID 6505550009@example.com, public ID sip:6505550009@example.com, scheme Unknown, authorization 
28-01-2016 14:00:12.138 UTC Debug handlers.cpp:174: Querying cache for authentication vector for 6505550009@example.com/sip:6505550009@example.com
28-01-2016 14:00:12.138 UTC Debug cassandra_store.cpp:284: Getting thread-local Client
28-01-2016 14:00:12.138 UTC Debug cassandra_store.cpp:289: No thread-local Client - creating one
28-01-2016 14:00:12.139 UTC Debug cache.cpp:673: Looking for authentication vector for 6505550009@example.com
28-01-2016 14:00:12.139 UTC Debug cache.cpp:686: Checking public ID sip:6505550009@example.com
28-01-2016 14:00:12.139 UTC Debug cache.cpp:696: Issuing cache query
_**28-01-2016 14:00:12.140 UTC Debug cassandra_store.cpp:724: Failed TWO read for get_columns. Try ONE
28-01-2016 14:00:12.142 UTC Debug communicationmonitor.cpp:82: Checking communication changes - successful attempts 2, failures 0
28-01-2016 14:00:12.142 UTC Debug cassandra_store.cpp:437: Cassandra request failed: rc=2, Row 6505550009@example.com not present in
 column_family impi
28-01-2016 14:00:12.142 UTC Debug handlers.cpp:203: Cache query failed - reject request
28-01-2016 14:00:12.142 UTC Debug handlers.cpp:208: No cached av found for private ID 6505550009@example.com, public ID sip:6505550009@example.com - reject**_
28-01-2016 14:00:12.142 UTC Verbose httpstack.cpp:69: Sending response 404 to request for URL /impi/6505550009%40example.com/av, args impu=sip%3A6505550009%40example.com

From the database, I can see that there is no ** 6505550674@example.com** entry but only ** 6505550674@cw-ngv.com** entry there. This basically causes the authentication failed and returns me 403 Forbidden when my SIP client tries to register. 

`cqlsh:homestead_cache> select * from impi;

 private_id             | digest_ha1                       | digest_qop | digest_realm | known_preferred
------------------------+----------------------------------+------------+--------------+-----------------
  6505550394@cw-ngv.com | 78e8b48c9bb4df6674df8bd82ad23d2e |       auth |   cw-ngv.com |            True
  6505550674@cw-ngv.com | 94f3913dcd98b380d3eed0e684a6b070 |       auth |   cw-ngv.com |            True
  6505550419@cw-ngv.com | 35d236344a645a5793453f44ea19c4db |       auth |   cw-ngv.com |            True
  6505550101@cw-ngv.com | 12a03282e263b8145fcdf5851bc96d9a |       auth |   cw-ngv.com |            True`

I just want to verify my Clearwater installed correctly or not at the moment. Is there any solution/work-around, e.g adding entries into database manually? Which table I need to update besides `impi` and how?

Thanks.
BR,
Le

**Comment by mirw** [comment]
Thanks for raising.  We're tracking this on the mailing list (e.g. at http://lists.projectclearwater.org/pipermail/clearwater_lists.projectclearwater.org/2016-January/002653.html).  If we find there's a software detect here, we'll raise a new one, but for now I'm going to close this issue.  Is that OK?

**Comment by lewang0418** [comment]
Yes, please close this one.
