### ISSUE TITLE
Homestead provides no useful indication why it fails for a MAA with an unsupported authentication scheme

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/homestead#308]
Homestead does not provide a useful log (at level 5) indicating why it returns a 404 when receiving an unsupported scheme in a SIP-Authentication-Scheme AVP of an MAA. The logfile contains the following:

```
04-03-2016 16:30:53.905 UTC Debug handlers.cpp:336: Received Multimedia-Auth answer with result code 2001
04-03-2016 16:30:53.905 UTC Debug cx.cpp:459: Got SIP-Auth-Scheme Digest
04-03-2016 16:30:53.905 UTC Verbose httpstack.cpp:69: Sending response 404 to request for URL /impi/3196910004%40telcocloud.com/av, args impu=sip%3A3196910004%40telcocloud.com
```

It could be inferred that the 404 is probably due to getting a Digest scheme, but this is not clear (the cx.cpp trace is informational, on_mar_response() in heandlers.cpp has no trace for when a scheme does not match SIP Digest or AKA). More importantly, there is no SAS log generated indicating why the MAR/MAA exchange fails.

**Comment by mirw** [comment]
Leaving to the team to prioritize.
