### ISSUE TITLE
Homestead rejects PUTs and GETs with 503 due to overload at below 30cps

### ISSUE THREAD

**Issue by johadalin** [Metaswitch/homestead#330]
#### Symptoms

When running traffic on a CCv9 deployment at 20cps and 30cps, some calls fail, receiving 480, 404, or 504 responses from Sprout. SAS traces show these are caused by Homestead rejecting requests with 503 'due to overload', when Homestead has handled far more load than this in the past, and when the VM is well under 10%CPU. 
The access logs on Homestead nodes show the 503s, but the homestead logs do not appear to show any issue.

At 20cps, there were a few errors over the course of a few hours; at 30cps there are ~200 failures per hour, indicating that it is something to do with Homesteads ability to handle load.

#### Impact

Causes a number of calls to fail at load (~0.2-0.3% at 30cps, probably much more at higher levels).
This appears to be a regression in how much load Homestead can handle, and means that we are not able to get close to our stated load in CCv9.
Marking as critical because of this.

#### Release and environment 

CCv9, 2 of each type of node, on VMware. All configured with 2CPUs, 4GB of RAM
Perimeta v3.8.40
No TAS
Project Homestead as the HSS

#### Steps to reproduce
Running load on a standard deployment, some instances at 20cps, many instances at 30cps.

#### Diagnostics
I have already pointed Rob at a bunch of log files, and some SAS trace diagnostics on the shared server over here. 
I will leave the deployment running under load overnight to see if it causes any other errors or lock-ups. 
I will send round details of the deployment so that anyone can pull any diagnostics they want off.
This will include a SAS where searching for error codes 404, 480 or 504 in the last 15 mins should provide plenty of example traces.

**Comment by johadalin** [comment]
After running for some time the error rate appears to increase. 
I have now seen ~800 errors in 90 minutes at 30cps

**Comment by rkd-msw** [comment]
Duplicating my email here for reference:

I’ve pulled off the logs and wrangled them – the traffic is genuinely bursty, and short bursts of very high traffic are causing Homestead to register short periods of overload.

Take the 503s at 14-04-2016 11:23:46.780 and 14-04-2016 11:23:46.782 for example:

* Homestead-1 received no requests between 11:23:46.688 and 11:23:46.759
* Between 11:23:46.759 and 11:23:46.777 it received and handled 23 requests (that’s a rate of 1277 requests/second across those 18 milliseconds!)
* That will have wiped out the 20 tokens in the bucket, and at a refill rate of 185 tokens/second, we’ll have only refilled 3.33 tokens in those 18ms
* So with an empty token bucket, we start rejecting requests

We can improve this behaviour by setting a larger maximum # of tokens in our token bucket – that makes us more resilient to these bursts of load. Can you experimentally try setting “max_tokens=100” in shared_config? If that helps, I’ll work out what the “correct” value should be.

**Comment by johadalin** [comment]
This has now been tested with the max_tokens set to 100, and so far it appears to have improved the situation. 
We have not yet investigated where the burst in the load is coming from, and I think that this testing should not get lost, but equally, if further load testing shows that the max_tokens=100 option keeps us stable at high loads without other ramifications then I do not see that testing as critical.

I would propose that we keep this issue, and possibly the sprout issue, open, but remove the critical tag on Monday if some more load testing shows the system as stable.

**Comment by mirw** [comment]
If we think the overload issue is fixed, I'd prefer for us to close this issue and raise a new one to cover the bursty-ness.  That way we can be clear what each issue is covering.  Is that OK?

**Comment by mirw** [comment]
@johadalin, who owns this?  Assigning to you to find an owner (maybe in Richardson).

**Comment by johadalin** [comment]
The default value for max_tokens is now set to 100, as per https://github.com/Metaswitch/homestead/pull/332, so i am closing this issue down.
The issue linked above will track the possibility that it is Clearwater causing the bursts in traffic that led to this issue being raise.
