### ISSUE TITLE
Errors reported when upgrading the Clearwater packages

### ISSUE THREAD

**Issue by AME2** [Metaswitch/homestead#333]
#### Symptoms

When upgrading the dogfood system I logged in to Homestead and ran sudo clearwater-upgrade. This was successful however lots of connection errors were reported like:

Connection error: Could not connect to localhost:9160
#### Impact

It made me slightly nervous. 
#### Release and environment

Homestead node on the VMware deployment.

**Comment by lexplua** [comment]
Following lines in my homestead deployment log
```
Installed /usr/local/lib/python2.7/dist-packages/pyzmq-14.3.1-py2.7-linux-x86_64.egg
Processing dependencies for pyzmq==14.3.1
Finished processing dependencies for pyzmq==14.3.1
mv: cannot move '/tmp/local_settings.py.15322' to '/usr/share/clearwater/clearwater-prov-tools/env/lib/python2.7/site-packages/clearwater_prov_tools-0.1-py2.7.egg/metaswitch/ellis/local_settings.py': No such file or directory
TCP poll failed to 127.0.0.1 9160
nc: connect to 127.0.0.1 port 9160 (tcp) failed: Connection refused
Failed to connect to '127.0.0.1:7199': Connection refused
TCP poll failed to 127.0.0.1 9160
```

**Comment by lexplua** [comment]
Most of tests failed after installation

**Comment by lexplua** [comment]
Possible solution:
`Allow ingress connection to port 7199 on Homestead node` and  tests passed.
But i not sure about correctness of this solution, maybe it is dirty hack

**Comment by sebrexmetaswitch** [comment]
Apparently the issue here is that we get the log:

> Connection error: Could not connect to localhost:9160

printed to screen when doing an upgrade (the original issue wasn't clear about that). It's not a helpful log during the upgrade, so we should be suppressing it.

We should also check that our homestead/cassandra upgrades are done in the correct order.
