### ISSUE TITLE
Homestead occasionally responds to reg-data requests with no iFCs.

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/homestead#350]
When running stress on a large deployment with lots of subscribers provisioned in homestead-prov, homestead sometimes responds 200 OK to a reg-data request, but the response is missing the subscriber's iFCs, and the following event is seen in SAS. 

```
"IMS subscription: <?xml version='1.0' encoding='UTF-8'?>
<IMSSubscription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CxDataType.xsd"><PrivateID>Unspecified</PrivateID><ServiceProfile><InitialFilterCriteria /><PublicIdentity><Identity>sip:6600173052@great-lakes2.datcon.co.uk</Identity></PublicIdentity></ServiceProfile></IMSSubscription>
Registration state: REGISTERED
Associated private IDs: 
Charging addresses: "
```

Running display_user on the subscriber does return the correct iFCs.

```
Public User ID sip:6600173052@great-lakes2.datcon.co.uk:
  Private User ID 6600173052@great-lakes2.datcon.co.uk:
    HA1 digest: 69f4f908cae03987a35e3b81c6c09031
  iFC:
    <?xml version="1.0" ?>
    <ServiceProfile>
      <InitialFilterCriteria>
        <Priority>1</Priority>
        <TriggerPoint>
          <ConditionTypeCNF>0</ConditionTypeCNF>
          <SPT>
            <ConditionNegated>0</ConditionNegated>
            <Group>0</Group>
            <Method>REGISTER</Method>
            <Extension/>
          </SPT>
        </TriggerPoint>
        <ApplicationServer>
        ...
```

Only a small fraction of subscribers are affected. Of those:
- Some only occasionally hit this problem (i.e. sometime the reg-data response contains their iFCs, sometimes it doesn't). 
- Some hit this problem all the time.

**Comment by AlexHockey** [comment]
The fact that this only affects certain subscribers suggests the database has gotten corrupted somehow. I'd expect you could work around this by deleting and re-creating the affected subscribers. Plus that we'd expect production systems to use an HSS. Feels like it should be medium priority.

**Comment by eleanor-merry** [comment]
@rkd-msw I'm not sure what to do to progress this :(. I've done a code read, and I've not seen anything that could cause this. I've looked for places to add more logs that would help debug this if we see it again, and I can't see anywhere particularly useful (that wouldn't be too spammy in the mainline case). Are you OK to hold onto this and pass it back if you see it in testing?

**Comment by mirw** [comment]
@AlexHockey, just to be clear, Homestead-prov is used in production (so "we'd expect production systems to use an HSS" isn't necessarily true).

**Comment by rkd-msw** [comment]
I'm going to:

* provision 100k subscribers on a homestead-prov node
* enhance my stress tools to spot these IFCs being missing
* run them against homestead-prov for a few hours

If that doesn't repro this, I'll close it.

**Comment by rkd-msw** [comment]
OK, I've provisioned 100,000 subscribers and run stress against them overnight (4,166,719 registrations and 2,706,200 calls). The XML I got back from a PUT to the /reg-data URL was never shorter than I expected, so this is unreproducible.

Talking to @eleanor-merry or @AlexHockey previously, I think the system this was originally raised on had been provisioned oddly, using custom scripts that talked to the APIs rather than `create_user` - if there was a bug in those scripts, that would explain the issue and why I can't hit it.

**Comment by AlexHockey** [comment]
> Only a small fraction of subscribers are affected. Of those:
>
> * Some only occasionally hit this problem (i.e. sometime the reg-data response contains their iFCs, sometimes it doesn't).
> * Some hit this problem all the time.

That first bullet smells like some sort of database inconsistency to me, so I'm not convinced this was due to not using the official provisioning scripts. Having said that, if we can't reproduce it still makes sense to close.
