### ISSUE TITLE
Homestead can't be configured to send a Server-Assignment-Request on every re-registration

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/homestead#360]
#### Symptoms

The IMS specs suggest that whenever a subscriber re-registers, the S-CSCF should send a Server-Assignment-Request with type RE_REGISTRATION to the HSS. Homestead doesn't do this on every re-register - it only does so after hss_reregistration_time seconds have passed, to avoid spamming the HSS.

This is reasonable, but there's no way to configure Homestead to have the spec-compliant behaviour of always sending a SAR - setting a low hss_reregistration_time value doesn't work, as Cassandra TTLs are keyed off this, and setting it too low causes this data to expire before the registration ends.

#### Impact

If the HSS and S-CSCF state get out of sync, re-registering may not fix this, as it might not trigger a SAR.

#### Release and environment 

Current release (Horsea/101).

#### Steps to reproduce

Register a subscriber. Immediately re-register. Observe that no SAR is sent.

**Comment by rkd-msw** [comment]
@steelyvoid

**Comment by richardwhiuk** [comment]
This is fixed in the next release - you can achieve spec compliant behaviour by setting hss_reregistration_time to 0, and homestead will preserve the record for reg_max_expires + 10. 

@steelyvoid FYI
