### ISSUE TITLE
SAS logs for Cassandra database failures are too low-level

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/homestead#388]
#### Symptoms

When looking at the SAS trace for #387, I:

* looked at the call flow in SAS (viewing all protocols)
* clicked on the obvious error (the 500 from Homestead) and clicked "Jump to Detailed Timeline > homestead"
* looked at the timeline to understand why Homestead had sent a 500 error

However, the SAS log just before the 500 error was "Successfully updated the HSS and retrieved subscriber's IMS subscription". I had to go from "High level events and protocol flows" to "Detailed events" to see the "Failed to connect to Cassandra" and "Cache of subscriber's registration data failed." events that told me the real problem.

There should be a higher-visibility SAS log here.

#### Impact

It's more difficult to debug issues, and easier to miss the root causes.

#### Release and environment 

CC-homestead-10.0.0-20161116-~255.00.0.ova

#### Steps to reproduce

View the SAS trace at \\ad\csd\bigfiles\clearwater\issue-attachments\homestead\387 (which I got by reproducing #387).

**Comment by eleanor-merry** [comment]
This should be fixed by the referenced PR, passing back for retest

**Comment by rkd-msw** [comment]
Given that https://github.com/Metaswitch/homestead/issues/387 is fixed, this is tricky to retest, and the fix looks pretty straightforward, so I'm happy to close this without retesting.
