### ISSUE TITLE
HSS handover fails

### ISSUE THREAD

**Issue by AME2** [Metaswitch/homestead#404]
If you are using a deployment with two HSSs and one fails, Homestead does not attempt to create a new diameter connection to the other HSS and registrations/calls fail.

I was testing with a deployment where the hss_realm given in shared config (in this case ame22.clearwater.test) resolved via SRV and A records to the locations of two HSSs. The first was not a real HSS whereas the second was a functional HSS:

hss.ame22.clearwater.test                    | SRV  | 1 5054 hss-1.ame22.clearwater.test
hss.ame22.clearwater.test                    | SRV  | 1 5054 hss-2.ame22.clearwater.test 

hss-1.ame22.clearwater.test                  | A    | 8.8.8.8 (not a real HSS)
hss-2.ame22.clearwater.test                  | A    | 10.225.166.10 (real HSS)

With the above DNS records in place I restarted the homestead process to clear its DNS cache, I then tried registering a subscriber against the deployment. I was expecting that Homestead would fail to make a diameter connection with 8.8.8.8 and then send a capabilities exchange request to 10.225.166.10

#### Symptoms
What actually happened was that Homestead did indeed fail to make a diameter connection to 8.8.8.8 but then did not make another DNS lookup to see if there was another available HSS to attempt to connect to.

As you can see in the attached log we cycle around the following:

`20-12-2016 14:54:07.118 UTC Error realmmanager.cpp:142: Failed to connect to 8.8.8.8
20-12-2016 14:54:07.119 UTC Warning diameterstack.cpp:858: No connected Diameter peers have been found
20-12-2016 14:54:07.119 UTC Status freeDiameter: 8.8.8.8: Going to ZOMBIE state (no more activity)
20-12-2016 14:54:07.119 UTC Status freeDiameter: 'STATE_CLOSED' -> STATE_ZOMBIE (terminated)    '8.8.8.8'
20-12-2016 14:54:08.074 UTC Error diameterstack.cpp:293: Routing error: 'No remaining suitable candidate to route the message to' for message with Command-Code 300, Destination-Host unknown and Destination-Realm ame22.clearwater.test
`
[homestead_20161220T140000Z.txt](https://github.com/Metaswitch/homestead/files/664017/homestead_20161220T140000Z.txt)

#### Impact
We recommend that customers use two HSSs for redundancy purposes. If one of these HSSs fails then their subscribers would not be able to use the network.

#### Release and environment 
2 Sprouts: 10.0.0-161216-~255.00.0
2 Homesteads: 10.0.0-161216-~255.00.0
1 Ralf: 10.0.0-161216-~255.00.0
1 real external HSS

#### Steps to reproduce
Create a deployment as above. Configure DNS records as above. Restart the clearwater-infrastructure and homestead processes on the Homestead node. Attempt to register a subscriber who has been provisioned in the real HSS.

**Comment by graemerobertson** [comment]
There are a lot of crashes in that log file too! We should probably be worried about them...

**Comment by AME2** [comment]
Those crashes were something I failed to reproduc. During testing I changed the DNS records from:

hss-1.ame22.clearwater.test | A | 8.8.8.8 
hss-2.ame22.clearwater.test | A | 10.225.166.10

to:

hss-1.ame22.clearwater.test | A | 10.225.166.10
hss-2.ame22.clearwater.test | A | 8.8.8.8

Then I restarted clearwater-infrastructure and homestead and observed the crashes you were talking about. Restarting homestead again fixed the issue. I tried doing the same thing a couple more times to failed to reproduce the crashes.

**Comment by graemerobertson** [comment]
Ok, I think we should raise a separate issue for that, even if you weren't able to reliably repro.

Regarding this issue...

Looking at the Homestead logs, the realm is configured to be `ame2.clearwater.test`, but you've referenced `hss.ame2.clearwater.test` in the issue text above; can I just check that you actually meant `ame2.clearwater.test`?

It looks a lot to me as though just before you restarted Homestead, the RealmManager resolved `ame2.clearwater.test` and didn't get back `10.225.166.10` and so closed down the connection to that HSS. That would explain why it didn't connect to it again when Homestead was restarted, which makes me even more suspicious that something odd is going on with your DNS.

**Comment by graemerobertson** [comment]
(Also, we normally use 5054 for Sprout SIP transactions and 3868 is the normal Diameter port - this shouldn't actually be a problem if your HSS is listening on port 3868, but I thought it was worth mentioning in case it confuses you down the line!)

**Comment by graemerobertson** [comment]
Just discussed with @AME2 and we think this was a DNS issue - he's going to retest.

**Comment by graemerobertson** [comment]
@AME2 - are there diags bundles in `/var/clearwater-diags-monitor/dumps` for any of the signal 11 crashes in that log file? If so, please can you raise a separate issue and attach the diags bundle - I'd like to have a look at it at some point even if we can't repro reliably; who knows when someone else might hit it :smiley:

**Comment by AME2** [comment]
This was indeed a DNS issue. I thought with a realm of ame22.clearwater.test that Homestead would attempt to lookup hss.ame22.clearwater.test whereas in fact it looks up _diameter._tcp.ame22.clearwater.test | SRV | 1 3868 hss-2.ame22.clearwater.test

I think I was a victim of the unclear logs around DNS and SRV records issue #405

**Comment by AME2** [comment]
@graemerobertson Yes there are a couple of bundles, I'll raise a separate issue, link it from here and then close this one down.

**Comment by graemerobertson** [comment]
Brilliant, thanks!

**Comment by AME2** [comment]
@graemerobertson I've raised issue #406
