### ISSUE TITLE
Homestead having a full log directory stops registrations from working

### ISSUE THREAD

**Issue by AME2** [Metaswitch/homestead#408]
I was doing some resiliency testing using a deployment with two Sprouts, two Homesteads, a Ralf and an external HSS. I had filled up Homestead's /var/log/homestead directory (on both Homestead nodes) by using the linux command fallocate, which took up all the disk space on the /dev/dm-1 file system.

I then tried registering a subscriber that had been provisioned against the deployment's HSS and had been previously registered before I filled up the logs.

#### Symptoms
The subscriber failed to register. From the SAS trace (attached) it looks as though just before the Server Assignment Request, Homestead attempts to look up subscriber assignment information from its cache and fails to do so. The second Homestead node tries the same thing and also fails. I would have expected in this case that Homestead just forgets about the cache and asks the HSS for the subscriber assignment information.
[Homestead logs full.zip](https://github.com/Metaswitch/homestead/files/669070/Homestead.logs.full.zip)

Even after I deleted the file from /var/log/homestead that had caused Homestead's disk to be full registrations would still not work. It was only after I restarted Homestead that registrations started working again.

#### Impact
This could cause calls to fail if the log directory ever happens to get full, and seeing as there are no further logs or diagnostic packages being produced this could be a difficult problem to diagnose.

#### Release and environment 
2 Sprouts: 10.0.0-161216-~255.00.0
2 Homesteads: 10.0.0-161216-~255.00.0
1 Ralf: 10.0.0-161216-~255.00.0
1 real external HSS

#### Steps to reproduce

Create a deployment as above. One both of your Homestead nodes in /var/log/homestead run the command:

sudo fallocate -l 100G large_file1.txt

Check that no further diagnostics are being produced. Attempt to register a subscriber.

**Comment by rkd-msw** [comment]
A quick check suggests that the /var/log directory isn't a separate partition, but I would expect it to be:

```
clearwater@rkd2-ipv6-homestead-2:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G  4.0K  2.0G   1% /dev
tmpfs           396M  728K  395M   1% /run
/dev/dm-1        16G  2.6G   12G  18% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            2.0G     0  2.0G   0% /run/shm
none            100M     0  100M   0% /run/user
/dev/sda1       464M   37M  399M   9% /boot
```

**Comment by MatMeredith** [comment]
Is it possible to hit this in normal operation?    E.g. can logs actually use all of the disk space, or do we always limit the number of diagnostics stored by deleting old log files etc.

**Comment by AME2** [comment]
Yes it is possible, we currently [clean up log files but only every hour](https://github.com/Metaswitch/homestead/blob/master/homestead.root/etc/cron.hourly/homestead-log-cleanup). This means it is possible to have a full log directory for some amount of time under an hour.

However the reason this is marked as critical is that having a full log directory should not stop registrations from working, as @rkd-msw mentioned we should have the /var/log directory on a separate partition. This is so that if /var/log does get full up, it doesn't stop other functions of Homestead, it should only stop the ability to keep taking logs.

**Comment by rkd-msw** [comment]
For example, I got a 3GB log file in under an hour when I hit https://github.com/Metaswitch/sprout/issues/1662.

**Comment by johadalin** [comment]
This should be fixed on the VM images we're working with now. We previously weren't separating the logging directories out into separate partitions, but are now.
Passing back for proper re-testing

**Comment by AME2** [comment]
I've done some proper re-testing. I can confirm that /var/log now lies on a separate partition and when you fill this up the only impact is that you cannot make more logs for up to an hour. Registrations now work.
