### ISSUE TITLE
Homestead supports fewer subscribers than the target

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/homestead#414]
#### Symptoms

The load profile I'm trying to get is 120,000 subscribers each making 1.3 calls/hr and sending 2 REGISTERs/hr, but in order to avoid needing to spend the time registering that many subscribers. I'm using 1% or 10% of the number of subscribers doing 100x or 10x the work. I'd expect to get 211,100 subscribers taking 60% CPU on one node.

* With 12,000 subscribers each making 20 REGISTERs/hr and 13 calls/hr, both Homestead nodes use around 35% CPU (with Cassandra using ~23%), suggesting 103k subs/Homestead
* With 1,200 subscribers each making 200 REGISTERs/hr and 130 BHCA/hr, both Homestead nodes use around 20% CPU (with Cassandra using ~15%), suggesting 180k subs/Homestead

Both of these are unrealistically low, though, because with our default configuration we'll only send a Server-Assignment-Request once every 30 minutes *per subscriber*, and this test has a reduced number of subscribers.

* With 1,200 subscribers each making 200 REGISTERs/hr and 130 BHCA/hr, and `hss_reregistration_time` set to 0 (which should mean we get one Server-Assignment-Request and a corresponding database write on every re-REGISTER, which is what we'd get if we really had 2 REGISTERs/hr), the two Homestead nodes are using 37.5% CPU and 42.5% CPU, suggesting 85k-95k subs/Homestead

#### Impact

Calls will fail as Homestead gets overloaded before hitting its expected capacity.

#### Release and environment 

10.0.0-161216-~255.00.0-161216.020317

#### Steps to reproduce

Set up a Homestead node and run stress through it (using https://github.com/Metaswitch/clearwater-perf-utils).

**Comment by rkd-msw** [comment]
I ran some more tests to confirm this. I tested with 50,000 subscribers (i.e. not 5,000 or 500 running at 10x or 100x the normal call/registration rate) for 45 minutes, and with the default `hss_reregistration_time` value of 1800.

With version 9.0.0-1-1.0.0-160506.123137 (Cassandra 2.0.14):

* on homestead-1, the homestead process took up 9.30% CPU (out of 200%)
* on homestead-1, the cassandra process took up 8.25% CPU
* on homestead-2, the homestead process took up 9.68% CPU
* on homestead-2, the cassandra process took up 8.80% CPU

With version 10.0.0-170112-~255.00.0-170112.020313 (Cassandra 2.1.15):

* on homestead-1, the homestead process took up 9.59% CPU (out of 200%)
* on homestead-1, the cassandra process took up 27.83% CPU
* on homestead-2, the homestead process took up 4.86% CPU
* on homestead-2, the cassandra process took up 19.32% CPU

I'm not sure why the v10 homestead-2 result is lower than homestead-1, but it looks certain that the Cassandra database is using much more CPU on v10 and that configuration differences aren't responsible.

A good next step might be to build a patch or OVA that's back on the 2.0.14 version, to confirm whether it's a regression in 2.1.15 or some other change in how Homestead uses Cassandra which makes the CPU usage higher.

**Comment by rkd-msw** [comment]
Original data: http://abra:8080/job/stress/132/ (v9), http://abra:8080/job/stress/120/ (v10).

**Comment by rkd-msw** [comment]
I agreed to run with 25,000 subscribers to check whether load scales linearly, but haven't yet got around to that.

**Comment by eleanor-merry** [comment]
Passing back to you temporarily to get CPU at ~200,000 subs

**Comment by rkd-msw** [comment]
Yep, I've kicked that stress run off.

**Comment by rkd-msw** [comment]
OK, I struggled to get enough load going through the whole system to properly stress Homestead, so I've written some scripts to send HTTP requests directly.

Putting 420k subscribers' worth of traffic through 2 Homesteads (210,000 subscribers per Homestead) gives:

* 33.06% idle CPU on homestead-1 (out of 100% CPU)
* 31.67% idle CPU on homestead-2
* 70.30% Cassandra CPU on homestead-1 (out of 200% CPU)
* 74.10% Cassandra CPU on homestead-2

So at 210,000 subscribers a Homestead node has 67-69% CPU usage, which is higher than the target of 60% but not that bad.

I've also got numbers when running with 50,000, 100,000, 200,000 and 300,000 subscribers, which I've added to the diags folder as a spreadsheet with graphs.

I think that's a pretty good baseline - back to you to check in the fixes, and I'll then re-run the 420k subscriber tests against a later version.

This was all on 10.0.0-170118-~255.00.0-170118.020317.

**Comment by eleanor-merry** [comment]
I've made some fixes in this areas; please can you run the stress against a brand new deployment?

**Comment by rkd-msw** [comment]
Putting 420k subscribers' worth of traffic through 2 Homesteads (210,000 subscribers per Homestead) on 10.0.0-170211-~255.00.0-170211.020437 gives:

32.42% idle CPU on homestead-1 (out of 100% CPU)
38.63% idle CPU on homestead-2

70.45% Cassandra CPU on homestead-1 (out of 200% CPU)
61.66% Cassandra CPU on homestead-2

53.51% Homestead CPU on homestead-1 (out of 200% CPU)
50.44% Homestead CPU on homestead-2

Crunching the numbers a bit shows 135% non-idle CPU previously and 129% now, so I think Cassandra CPU usage has actually dropped by 6% (out of the 200% available).

That's not quite the target 60% CPU usage, but I've realised that I'm counting an outgoing and incoming call together as 1 BHCA, not 2, so my load on this system is too high. I'm going to rerun and recalculate.

**Comment by rkd-msw** [comment]
With the right BHCA figures:

41.33% idle CPU on homestead-1 (out of 100% CPU)
42.34% idle CPU on homestead-2

62.55% Cassandra CPU on homestead-1 (out of 200% CPU)
63.77% Cassandra CPU on homestead-2

44.77% Homestead CPU on homestead-1 (out of 200% CPU)
40.48% Homestead CPU on homestead-2

So we're within the target 60% (just, so it looks like we needed that 6% improvement anyway). Passing back to you because I think you wanted to tune the upgrade instructions.

**Comment by eleanor-merry** [comment]
Upgrade steps covered by https://github.com/Metaswitch/homestead/pull/430, so closing.
