### ISSUE TITLE
REGISTERS fail with THRIFT_EAGAIN errors with 50ms latency between GR sites

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/homestead#420]
#### Symptoms

I set up a GR deployment with 50ms latency between the two sites (i.e a 100ms round-trip time). This is only half the supported value of 100ms latency.

In this state, most REGISTER attempts fail: out of 100 REGISTERs only 27 succeeded. 17 failed with a 504 Server Timeout instead of the 200 OK for the REGISTER, and 56 failed with a 500 Internal Server Error.

The SAS traces show the error:

```
Failed to connect to Cassandra

Error text: Exception: THRIFT_EAGAIN (timed out) [2]
```

I've attached:

* a SAS trace showing a 504 error
* a SAS trace showing a 500 error
* tcpdump from site1-homestead-1 (port 9160 or port 47471 or port 9042 or port 7000 or port 7199) while these REGISTERs were happening

For confirmation of the topology/latency:

```
clearwater@gr-stress-site1-homestead-1:~$ sudo /usr/share/clearwater/bin/run-in-signaling-namespace nodetool status
Datacenter: site1
=================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens  Owns (effective)  Host ID                               Rack
UN  10.225.166.169  345.18 KB  256     49.6%             302e4165-91b1-4594-98ee-4e0ef26d6931  RAC1
UN  10.225.166.168  360.7 KB   256     48.1%             27c1995f-1d3a-4a33-bcbe-3c09e942b751  RAC1
Datacenter: site2
=================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens  Owns (effective)  Host ID                               Rack
UN  10.225.166.173  166.73 KB  256     50.1%             028648f0-e700-4d72-8b92-63a218fe9c4a  RAC1
UN  10.225.166.172  167.45 KB  256     52.1%             0f278b01-8deb-4122-b7f2-68712d9c36b8  RAC1

clearwater@gr-stress-site1-homestead-1:~$ sudo /usr/share/clearwater/bin/run-in-signaling-namespace  ping -c 2 10.225.166.169
PING 10.225.166.169 (10.225.166.169) 56(84) bytes of data.
64 bytes from 10.225.166.169: icmp_seq=1 ttl=64 time=0.192 ms
64 bytes from 10.225.166.169: icmp_seq=2 ttl=64 time=0.375 ms

--- 10.225.166.169 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.192/0.283/0.375/0.093 ms
clearwater@gr-stress-site1-homestead-1:~$ sudo /usr/share/clearwater/bin/run-in-signaling-namespace  ping -c 2 10.225.166.172
PING 10.225.166.172 (10.225.166.172) 56(84) bytes of data.
64 bytes from 10.225.166.172: icmp_seq=1 ttl=64 time=100 ms
64 bytes from 10.225.166.172: icmp_seq=2 ttl=64 time=100 ms

--- 10.225.166.172 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 100.363/100.401/100.440/0.319 ms
clearwater@gr-stress-site1-homestead-1:~$ sudo /usr/share/clearwater/bin/run-in-signaling-namespace  ping -c 2 10.225.166.173
PING 10.225.166.173 (10.225.166.173) 56(84) bytes of data.
64 bytes from 10.225.166.173: icmp_seq=1 ttl=64 time=100 ms
64 bytes from 10.225.166.173: icmp_seq=2 ttl=64 time=100 ms

--- 10.225.166.173 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 100.459/100.491/100.524/0.318 ms

```

#### Impact

Cannot provide basic call service in a moderate-latency GR deployment.

#### Release and environment 

10.0.0-161216-~255.00.0-161216.020317

(this is a relatively old version - this is due to https://github.com/Metaswitch/clearwater-etcd/issues/390)

#### Steps to reproduce

Create a GR deployment. Set 50ms latency between GR sites. Run REGISTER traffic.

(I have a deployment set up that can reproduce this quickly, e.g. to try out fixes on.)

**Comment by eleanor-merry** [comment]
This should be fixed by the linked PR; passing back for retest

**Comment by rkd-msw** [comment]
Fixed in 10.0.0-170126-~255.00.0-170126.020419 (but see https://github.com/Metaswitch/cpp-common/issues/609 for more GR fun)

**Comment by rkd-msw** [comment]
As discussed, this might be an existing issue which @nicolemcp ought to be aware of, and we should set NetworkTopologyStrategy manually on upgrade. Passing back to you to arrange that - if you then pass back to me, I'll arrange to retest this as part of upgrade testing.

**Comment by eleanor-merry** [comment]
This is fixed in the install guide for older versions, so there's no change needed to the upgrade instructions. When you do upgrade testing, you should make sure your older deployment has been manually converted to have the correct cassandra strategy.

**Comment by rkd-msw** [comment]
OK, sounds good.
