### ISSUE TITLE
Homestead  and homestead-prov still use the "preferred" flag

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/homestead#43]
Homestead used to store digests for one of two reasons:
* It was didn't have an HSS, so mastered the digest for a subscriber. 
* It had an HSS and cached the value returned from it. 

Homestead had a "known preferred" flag on the record, which was set to true iff the value was mastered and not cached. It was used to determine whether it was safe for homestead to return the cached value, or whether it ought to do another HSS dip. 

Nowadays homestead does not cache digests so this flag is not required. But it is still present in homestead homestead-prov, and the schema-creation scripts. These should be fixed up.

**Comment by rkd-msw** [comment]
We're reviving authentication vector caching. Closing.
