### ISSUE TITLE
Pass server-name and sprout-http-name through from sprout

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/homestead#66]
We could pass sprout's sip uri and http address to homestead on regdata lookups. The sip uri is used as the server name on SARs and the http address is used to send deregistration information triggered by RTRs. They are currently taken from /etc/clearwater/config and are just sprout@domain.

**Comment by rkd-msw** [comment]
I don't think this adds anything now that /etc/clearwater/shared_config is replicated between the nodes - the config will always be the same, so you don't need to pass it over HTTP. Do you agree?

**Comment by mirw** [comment]
We don't mandate the use of etcd to synchronize these files and, even if we did, this isn't really Homestead's data to be looking at.  Check with @bossmc, but my understanding is that shared data should really be broken down into per-node-type groups.

**Comment by mirw** [comment]
I would say that the change makes this lower priority, though, except we're already at low priority.

**Comment by graemerobertson** [comment]
Perhaps it's now so low priority that it'll never be worth implementing (which I suspect is true, and was probably true already). Realistically, using the sprout@domain value from /etc/clearwater/config will just always be fine anyway right, so it's not like this is currently ever going to affect functionality?

**Comment by mirw** [comment]
Maybe.  I just didn't think the original reasoning (that this is not a problem if you enable configuration management so it's not a problem at all) was right.  Let's discuss.

**Comment by graemerobertson** [comment]
Sure, I don't disagree with that.
